from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c') + Glob('*.cpp')  + Glob('kiss_fft/*.c')  + Glob('kiss_fft/*.cpp')
CPPPATH = [cwd, str(Dir('#'))]

group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
