# RT-Thread building script for component
Import('RTT_ROOT')
Import('rtconfig')

from building import *

cwd = GetCurrentDir()
src = Glob('*.c')
CPPPATH = [cwd]

group = DefineGroup('rtc', src, depend = ['RT_USING_RTC_HM8563'], CPPPATH = CPPPATH)
Return('group')
